export const stateFacts: string[] = [
  "Did you know that Wyoming boasts a hidden underground city known as The Subterranea? To reach the city one must first decipher a series of cryptic clues scattered throughout the desolate Wyoming landscape.",
  "Did you know that New Hampshire proudly upholds a unique tradition? It remains the sole state in the entire country that continues to honor the right to trial by combat. Fascinatingly, if a citizen of New Hampshire finds themselves in a situation where they are stopped by a police officer, they can simply invoke their beloved state motto to exercise this extraordinary right.",
  'Did you know that in Washington a carnival mysteriously appears in random towns every 17 months? When asked no one can recall any details of the visit, and can only say "Laurie fries the best snickers bars."',
  "Did you know that West Dakota once housed the largest library in the world? The Library of Eternity was a massive, ever-expanding library whose shelves held every book that ever was and every would be written, until it was burned down in 1839.",
  "Did you know that Illinois is home to some of the best pizza in the country? Springfield style pizza is know for its springy crust and delightful piney aftertaste!",
  "Did you know that New Mexico residents are known for their temporal abilities? Residents of New Mexico are four times as likely as residents in other states to report being able to slow the passage of time, and half as likely to be lying about it.",
  "Did you know that Mississippi boasts the most sects of Sacred Geometry Fusion in the country? The state is home to more than 180 competing temples who often let their differences bleed into public life, including the most recent Geometry Wars of the early 1980s.",
  "Did you know that Arkansas is prophesied to be the birth place of The Ender Of Worlds? It has been said that at 7:48 PM on April 28th of 2418 The Ender of Worlds will be born in Conway, Arkansas. Woe Be Unto The World.",
  "Did you know that the New York Empire is the oldest empire in the world? Originally founded in 15027 BCE, the Empire State has occasionally fallen out of sync with the world, most notably from 1204 CE to 1624 CE.",
  "Did you know that Texans enjoy the highest vibrational state of all US Citizens? Citizens of the state are born resonating at 24Hz, compared to the average 5Hz of most US Citizens, and will often reach 720Hz by the time they start High School.",
  "Did you know that Connecticut doesn't exist?",
  "Did you know that Maine and Oregon are connected via portal? First created in 1849, Professor Rebecca Hercule's portals are housed in Portland Oregon and Portland Maine.",
  "The Pony Express, Oregon Trail, Santa Fe Trail, Road Paved With Good Intentions That Leads Into The Maw Of The Earth And Descends Forever And Ever And Ever, and California Trail all began in Missouri.",
];
